import json
import matplotlib.pyplot as plt
import os
import argparse
import numpy as np

"""
Visualization module for Multi-Agent Experiment Results.

This script reads the JSON reports generated by 'experiment_runner.py' and produces
static plots (PNG) for key metrics like Cooperation Rate and Entropy.

Fix 7: Now includes Nash Equilibrium and Social Optimum reference lines.
Fix 8: Adds per-trial variance analysis (individual trial trajectories).
"""

def plot_sweep_results(file_path):
    """
    Generates plots from a given experiment report file.
    
    Args:
        file_path (str): Path to the 'final_sweep_report.json' file.
        
    Outputs:
        - cooperation_plot.png: Cooperation Rate vs Rounds (with theoretical baselines)
        - entropy_plot.png: Behavioral Entropy vs Rounds
        - per_trial_variance.png: Individual trial trajectories for each config
    """
    print(f"Loading results from {file_path}...")
    with open(file_path, 'r') as f:
        data = json.load(f)
    
    output_dir = os.path.dirname(file_path)
    
    # ========================================
    # 1. Cooperation Rate with Theoretical Baselines
    # ========================================
    plt.figure(figsize=(12, 7))
    
    for entry in data:
        config = entry['config']
        metrics = entry['metrics']
        
        rounds = range(1, len(metrics['mean_cooperation']) + 1)
        mean_coop = metrics['mean_cooperation']
        std_coop = metrics['std_cooperation']
        
        mem = config.get('memory_limit', '?')
        agent_type = config.get('agent_type', 'llm')
        label = f"N={config['num_agents']}, M={config['multiplier']}, Mem={mem}"
        if agent_type != "llm":
            label += f" [{agent_type}]"
        
        plt.plot(rounds, mean_coop, marker='o', label=label, markersize=3)
        plt.fill_between(rounds, 
                         np.array(mean_coop) - np.array(std_coop), 
                         np.array(mean_coop) + np.array(std_coop), 
                         alpha=0.1)

    # Theoretical baselines
    max_rounds = max(len(entry['metrics']['mean_cooperation']) for entry in data)
    x_line = range(1, max_rounds + 1)
    plt.axhline(y=1.0, color='green', linestyle=':', linewidth=1.5, alpha=0.7, label='Social Optimum (100%)')
    plt.axhline(y=0.0, color='red', linestyle=':', linewidth=1.5, alpha=0.7, label='Nash Equilibrium (0%)')
    plt.axhline(y=0.5, color='gray', linestyle=':', linewidth=1.0, alpha=0.5, label='Random Baseline (50%)')

    plt.title("Cooperation Rate over Rounds", fontsize=14)
    plt.xlabel("Round", fontsize=12)
    plt.ylabel("Avg Contribution % (normalized)", fontsize=12)
    plt.ylim(-0.05, 1.15)
    plt.legend(fontsize=8, loc='lower right')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    
    output_img = os.path.join(output_dir, "cooperation_plot.png")
    plt.savefig(output_img, dpi=150)
    print(f"Saved plot to {output_img}")
    plt.close()

    # ========================================
    # 2. Entropy over Time
    # ========================================
    plt.figure(figsize=(12, 7))
    
    for entry in data:
        config = entry['config']
        metrics = entry['metrics']
        
        rounds = range(1, len(metrics['mean_entropy']) + 1)
        mean_ent = metrics['mean_entropy']
        
        mem = config.get('memory_limit', '?')
        label = f"N={config['num_agents']}, M={config['multiplier']}, Mem={mem}"
        plt.plot(rounds, mean_ent, marker='s', linestyle='--', label=label, markersize=3)

    plt.title("Behavioral Entropy over Rounds", fontsize=14)
    plt.xlabel("Round", fontsize=12)
    plt.ylabel("Entropy (bits)", fontsize=12)
    plt.legend(fontsize=8)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    
    output_img_ent = os.path.join(output_dir, "entropy_plot.png")
    plt.savefig(output_img_ent, dpi=150)
    print(f"Saved plot to {output_img_ent}")
    plt.close()
    
    # ========================================
    # 3. Gini Coefficient over Time
    # ========================================
    has_gini = any('mean_gini' in entry['metrics'] for entry in data)
    if has_gini:
        plt.figure(figsize=(12, 7))
        
        for entry in data:
            config = entry['config']
            metrics = entry['metrics']
            if 'mean_gini' not in metrics:
                continue
            
            rounds = range(1, len(metrics['mean_gini']) + 1)
            mem = config.get('memory_limit', '?')
            label = f"N={config['num_agents']}, M={config['multiplier']}, Mem={mem}"
            plt.plot(rounds, metrics['mean_gini'], marker='^', linestyle='-', label=label, markersize=3)

        plt.title("Reward Inequality (Gini Coefficient) over Rounds", fontsize=14)
        plt.xlabel("Round", fontsize=12)
        plt.ylabel("Gini Coefficient", fontsize=12)
        plt.ylim(-0.01, 0.5)
        plt.axhline(y=0.0, color='green', linestyle=':', alpha=0.5, label='Perfect Equality')
        plt.legend(fontsize=8)
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        
        output_img_gini = os.path.join(output_dir, "gini_plot.png")
        plt.savefig(output_img_gini, dpi=150)
        print(f"Saved plot to {output_img_gini}")
        plt.close()
    
    # ========================================
    # 4. Defector Ratio over Time
    # ========================================
    has_defector = any('mean_defector_ratio' in entry['metrics'] for entry in data)
    if has_defector:
        plt.figure(figsize=(12, 7))
        
        for entry in data:
            config = entry['config']
            metrics = entry['metrics']
            if 'mean_defector_ratio' not in metrics:
                continue
            
            rounds = range(1, len(metrics['mean_defector_ratio']) + 1)
            mem = config.get('memory_limit', '?')
            label = f"N={config['num_agents']}, M={config['multiplier']}, Mem={mem}"
            plt.plot(rounds, metrics['mean_defector_ratio'], marker='v', linestyle='-', label=label, markersize=3)

        plt.title("Defector Ratio over Rounds", fontsize=14)
        plt.xlabel("Round", fontsize=12)
        plt.ylabel("Fraction of Agents Contributing 0", fontsize=12)
        plt.ylim(-0.05, 1.05)
        plt.legend(fontsize=8)
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        
        output_img_def = os.path.join(output_dir, "defector_plot.png")
        plt.savefig(output_img_def, dpi=150)
        print(f"Saved plot to {output_img_def}")
        plt.close()
    
    # ========================================
    # 5. Convergence Summary (text report)
    # ========================================
    has_convergence = any('mean_time_to_convergence' in entry['metrics'] for entry in data)
    if has_convergence:
        summary_path = os.path.join(output_dir, "convergence_summary.txt")
        with open(summary_path, "w") as f:
            f.write("Convergence Summary\n")
            f.write("=" * 60 + "\n\n")
            f.write(f"{'Config':<30} {'Conv. Rate':>10} {'Mean Round':>12} {'Change Pts':>12}\n")
            f.write("-" * 64 + "\n")
            for entry in data:
                config = entry['config']
                metrics = entry['metrics']
                mem = config.get('memory_limit', '?')
                label = f"N={config['num_agents']}, M={config['multiplier']}, Mem={mem}"
                conv_rate = metrics.get('convergence_rate', 0)
                mean_conv = metrics.get('mean_time_to_convergence')
                change_pts = metrics.get('total_change_points', 0)
                
                conv_str = f"{mean_conv:.1f}" if mean_conv is not None else "N/A"
                f.write(f"{label:<30} {conv_rate:>9.0%} {conv_str:>12} {change_pts:>12}\n")
        print(f"Saved convergence summary to {summary_path}")
    
    # ========================================
    # 6. Per-Trial Variance Analysis
    # ========================================
    # Load raw trial data and plot individual trial trajectories
    raw_files = [f for f in os.listdir(output_dir) if f.startswith("raw_") and f.endswith(".json")]
    
    if raw_files:
        n_configs = len(raw_files)
        cols = min(3, n_configs)
        rows = (n_configs + cols - 1) // cols
        fig, axes = plt.subplots(rows, cols, figsize=(6 * cols, 4 * rows), squeeze=False)
        
        for idx, raw_file in enumerate(sorted(raw_files)):
            row, col = divmod(idx, cols)
            ax = axes[row][col]
            
            config_key = raw_file[len("raw_"):-len(".json")]
            
            with open(os.path.join(output_dir, raw_file), 'r') as f:
                trials = json.load(f)
            
            # Plot each trial's cooperation trajectory
            for trial in trials:
                coop = trial['metrics']['cooperation_rates']
                rounds = range(1, len(coop) + 1)
                ax.plot(rounds, coop, alpha=0.2, linewidth=0.8, color='blue')
            
            # Plot the mean
            if trials:
                all_coop = [t['metrics']['cooperation_rates'] for t in trials]
                mean_coop = np.mean(all_coop, axis=0)
                ax.plot(range(1, len(mean_coop) + 1), mean_coop, 
                       color='red', linewidth=2, label='Mean')
            
            ax.set_title(config_key, fontsize=10)
            ax.set_ylim(-0.05, 1.15)
            ax.axhline(y=0.0, color='red', linestyle=':', alpha=0.3)
            ax.axhline(y=1.0, color='green', linestyle=':', alpha=0.3)
            ax.grid(True, alpha=0.2)
            ax.legend(fontsize=7)
        
        # Hide empty subplots
        for idx in range(n_configs, rows * cols):
            row, col = divmod(idx, cols)
            axes[row][col].set_visible(False)
        
        fig.suptitle("Per-Trial Cooperation Trajectories", fontsize=14)
        plt.tight_layout()
        
        output_img_var = os.path.join(output_dir, "per_trial_variance.png")
        fig.savefig(output_img_var, dpi=150)
        print(f"Saved plot to {output_img_var}")
        plt.close(fig)
    
    print("All plots generated successfully.")


def plot_signaling_results(file_path):
    """
    Generates plots from a signaling game sweep report.
    
    Outputs:
        - deception_plot.png: Deception Rate over Rounds
        - trust_plot.png: Trust Rate over Rounds
        - deception_success_plot.png: Deception Success Rate
        - receiver_accuracy_plot.png: Receiver Accuracy
    """
    print(f"Loading signaling results from {file_path}...")
    with open(file_path, 'r') as f:
        data = json.load(f)
    
    output_dir = os.path.dirname(file_path)
    
    def _make_label(config):
        s = config.get('num_senders', '?')
        r = config.get('num_receivers', '?')
        t = config.get('topology', '?')
        m = config.get('memory_limit', '?')
        return f"S={s}, R={r}, T={t}, Mem={m}"
    
    # ========================================
    # 1. Deception Rate
    # ========================================
    plt.figure(figsize=(12, 7))
    for entry in data:
        config = entry['config']
        met = entry['metrics']
        if 'mean_deception_rate' not in met:
            continue
        rounds = range(1, len(met['mean_deception_rate']) + 1)
        label = _make_label(config)
        plt.plot(rounds, met['mean_deception_rate'], marker='o', label=label, markersize=3)
        if 'std_deception_rate' in met:
            plt.fill_between(rounds,
                             np.array(met['mean_deception_rate']) - np.array(met['std_deception_rate']),
                             np.array(met['mean_deception_rate']) + np.array(met['std_deception_rate']),
                             alpha=0.1)
    
    plt.axhline(y=0.0, color='green', linestyle=':', alpha=0.5, label='Perfect Truth-Telling')
    plt.axhline(y=1.0, color='red', linestyle=':', alpha=0.5, label='Total Deception')
    plt.axhline(y=0.5, color='gray', linestyle=':', alpha=0.3, label='Random')
    plt.title("Deception Rate over Rounds", fontsize=14)
    plt.xlabel("Round", fontsize=12)
    plt.ylabel("Fraction of Deceptive Messages", fontsize=12)
    plt.ylim(-0.05, 1.15)
    plt.legend(fontsize=7, loc='best')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "deception_plot.png"), dpi=150)
    print(f"Saved deception_plot.png")
    plt.close()
    
    # ========================================
    # 2. Trust Rate
    # ========================================
    plt.figure(figsize=(12, 7))
    for entry in data:
        config = entry['config']
        met = entry['metrics']
        if 'mean_trust_rate' not in met:
            continue
        rounds = range(1, len(met['mean_trust_rate']) + 1)
        label = _make_label(config)
        plt.plot(rounds, met['mean_trust_rate'], marker='s', linestyle='--', label=label, markersize=3)
    
    plt.axhline(y=1.0, color='blue', linestyle=':', alpha=0.5, label='Always Invest')
    plt.axhline(y=0.0, color='orange', linestyle=':', alpha=0.5, label='Always Pass')
    plt.title("Trust Rate (All Receivers) over Rounds", fontsize=14)
    plt.xlabel("Round", fontsize=12)
    plt.ylabel("Fraction of Receivers Investing", fontsize=12)
    plt.ylim(-0.05, 1.15)
    plt.legend(fontsize=7, loc='best')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "trust_plot.png"), dpi=150)
    print(f"Saved trust_plot.png")
    plt.close()
    
    # ========================================
    # 2b. Informed Trust Rate (excludes empty-inbox receivers)
    # ========================================
    has_informed = any('mean_informed_trust_rate' in entry['metrics'] for entry in data)
    if has_informed:
        plt.figure(figsize=(12, 7))
        for entry in data:
            config = entry['config']
            met = entry['metrics']
            informed = met.get('mean_informed_trust_rate', [])
            if not informed:
                continue
            # Filter None values for plotting
            rounds_plot = [r + 1 for r, v in enumerate(informed) if v is not None]
            vals_plot = [v for v in informed if v is not None]
            if not rounds_plot:
                continue
            label = _make_label(config)
            plt.plot(rounds_plot, vals_plot, marker='s', linestyle='--', label=label, markersize=3)

        plt.axhline(y=1.0, color='blue', linestyle=':', alpha=0.5, label='Always Invest')
        plt.axhline(y=0.0, color='orange', linestyle=':', alpha=0.5, label='Always Pass')
        plt.title("Informed Trust Rate over Rounds\n(Excludes receivers with no messages)", fontsize=14)
        plt.xlabel("Round", fontsize=12)
        plt.ylabel("Fraction of Informed Receivers Investing", fontsize=12)
        plt.ylim(-0.05, 1.15)
        plt.legend(fontsize=7, loc='best')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "informed_trust_plot.png"), dpi=150)
        print(f"Saved informed_trust_plot.png")
        plt.close()
    
    # ========================================
    # 3. Deception Success Rate
    # ========================================
    has_success = any('mean_deception_success' in entry['metrics'] for entry in data)
    if has_success:
        plt.figure(figsize=(12, 7))
        for entry in data:
            config = entry['config']
            met = entry['metrics']
            if 'mean_deception_success' not in met:
                continue
            rounds = range(1, len(met['mean_deception_success']) + 1)
            label = _make_label(config)
            plt.plot(rounds, met['mean_deception_success'], marker='^', label=label, markersize=3)
        
        plt.title("Deception Success Rate over Rounds", fontsize=14)
        plt.xlabel("Round", fontsize=12)
        plt.ylabel("Fraction of Lies → Invest", fontsize=12)
        plt.ylim(-0.05, 1.15)
        plt.legend(fontsize=7, loc='best')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "deception_success_plot.png"), dpi=150)
        print(f"Saved deception_success_plot.png")
        plt.close()
    
    # ========================================
    # 4. Receiver Accuracy
    # ========================================
    has_accuracy = any('mean_receiver_accuracy' in entry['metrics'] for entry in data)
    if has_accuracy:
        plt.figure(figsize=(12, 7))
        for entry in data:
            config = entry['config']
            met = entry['metrics']
            if 'mean_receiver_accuracy' not in met:
                continue
            rounds = range(1, len(met['mean_receiver_accuracy']) + 1)
            label = _make_label(config)
            plt.plot(rounds, met['mean_receiver_accuracy'], marker='D', label=label, markersize=3)
        
        plt.axhline(y=0.5, color='gray', linestyle=':', alpha=0.3, label='Random Accuracy')
        plt.title("Receiver Accuracy over Rounds", fontsize=14)
        plt.xlabel("Round", fontsize=12)
        plt.ylabel("Fraction of Optimal Decisions", fontsize=12)
        plt.ylim(-0.05, 1.15)
        plt.legend(fontsize=7, loc='best')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "receiver_accuracy_plot.png"), dpi=150)
        print(f"Saved receiver_accuracy_plot.png")
        plt.close()
    
    # ========================================
    # 5. Convergence Summary (text)
    # ========================================
    summary_path = os.path.join(output_dir, "convergence_summary.txt")
    with open(summary_path, "w") as f:
        f.write("Signaling Game Convergence Summary\n")
        f.write("=" * 70 + "\n\n")
        f.write(f"{'Config':<40} {'Conv. Rate':>10} {'Mean Round':>12} {'Change Pts':>12}\n")
        f.write("-" * 74 + "\n")
        for entry in data:
            config = entry['config']
            met = entry['metrics']
            label = _make_label(config)
            conv_rate = met.get('convergence_rate', 0)
            mean_conv = met.get('mean_time_to_convergence')
            change_pts = met.get('total_change_points', 0)
            conv_str = f"{mean_conv:.1f}" if mean_conv is not None else "N/A"
            f.write(f"{label:<40} {conv_rate:>9.0%} {conv_str:>12} {change_pts:>12}\n")
    print(f"Saved convergence summary to {summary_path}")
    
    print("All signaling game plots generated successfully.")


# ================================================================
# SUMMARY VISUALIZATIONS FOR LARGE SWEEPS
# ================================================================

def plot_signaling_summary(file_path):
    """
    Generates publication-quality summary plots for large signaling sweeps.
    
    Instead of 54 overlapping time-series, produces:
      1. Heatmap grids: S×R matrix for each topology×memory combo
      2. Faceted time-series: one subplot per topology×memory group
      3. Parameter effect bar charts: marginal effect of each dimension
    """
    print(f"Generating signaling summary plots from {file_path}...")
    with open(file_path, 'r') as f:
        data = json.load(f)
    
    output_dir = os.path.dirname(file_path)
    summary_dir = os.path.join(output_dir, "summary_plots")
    os.makedirs(summary_dir, exist_ok=True)
    
    # Extract unique parameter values
    topologies = sorted(set(e['config'].get('topology', '?') for e in data))
    memories = sorted(set(e['config'].get('memory_limit', 0) for e in data))
    senders = sorted(set(e['config'].get('num_senders', 0) for e in data))
    receivers = sorted(set(e['config'].get('num_receivers', 0) for e in data))
    
    # Metrics to plot
    metric_defs = [
        ('mean_deception_rate', 'Deception Rate', 'deception'),
        ('mean_trust_rate', 'Trust Rate', 'trust'),
        ('mean_deception_success', 'Deception Success Rate', 'deception_success'),
        ('mean_receiver_accuracy', 'Receiver Accuracy', 'receiver_accuracy'),
    ]
    
    # Build lookup dict: (topology, memory, senders, receivers) -> entry
    lookup = {}
    for entry in data:
        c = entry['config']
        key = (c.get('topology'), c.get('memory_limit'), c.get('num_senders'), c.get('num_receivers'))
        lookup[key] = entry
    
    # ========================================
    # 1. HEATMAP GRIDS: one figure per metric
    # ========================================
    for metric_key, metric_title, metric_slug in metric_defs:
        n_topo = len(topologies)
        n_mem = len(memories)
        
        if n_topo == 0 or n_mem == 0:
            continue
        
        fig, axes = plt.subplots(n_topo, n_mem, figsize=(4 * n_mem + 1, 4 * n_topo + 0.5),
                                  squeeze=False)
        
        for ti, topo in enumerate(topologies):
            for mi, mem in enumerate(memories):
                ax = axes[ti][mi]
                
                # Build S×R matrix of average metric value
                matrix = np.full((len(senders), len(receivers)), np.nan)
                for si, s in enumerate(senders):
                    for ri, r in enumerate(receivers):
                        entry = lookup.get((topo, mem, s, r))
                        if entry and metric_key in entry['metrics']:
                            vals = entry['metrics'][metric_key]
                            valid = [v for v in vals if v is not None]
                            matrix[si][ri] = np.mean(valid) if valid else np.nan
                
                im = ax.imshow(matrix, cmap='RdYlGn_r' if 'deception' in metric_slug else 'RdYlGn',
                               vmin=0, vmax=1, aspect='auto', origin='lower')
                
                # Annotate cells
                for si in range(len(senders)):
                    for ri in range(len(receivers)):
                        val = matrix[si][ri]
                        if not np.isnan(val):
                            color = 'white' if val > 0.6 or val < 0.2 else 'black'
                            ax.text(ri, si, f'{val:.0%}', ha='center', va='center',
                                    fontsize=10, fontweight='bold', color=color)
                
                ax.set_xticks(range(len(receivers)))
                ax.set_xticklabels([str(r) for r in receivers])
                ax.set_yticks(range(len(senders)))
                ax.set_yticklabels([str(s) for s in senders])
                
                if ti == n_topo - 1:
                    ax.set_xlabel('Receivers', fontsize=10)
                if mi == 0:
                    ax.set_ylabel(f'{topo.upper()}\nSenders', fontsize=10)
                
                ax.set_title(f'Mem={mem}', fontsize=11)
        
        fig.suptitle(f'{metric_title} — Average Across All Rounds\n(rows=topology, cols=memory)',
                     fontsize=14, fontweight='bold')
        fig.colorbar(im, ax=axes, shrink=0.6, label=metric_title)
        plt.tight_layout(rect=[0, 0, 0.92, 0.93])
        
        path = os.path.join(summary_dir, f'heatmap_{metric_slug}.png')
        fig.savefig(path, dpi=150)
        print(f"  Saved {path}")
        plt.close(fig)
    
    # ========================================
    # 2. FACETED TIME-SERIES: grouped by topology × memory
    # ========================================
    for metric_key, metric_title, metric_slug in metric_defs:
        n_topo = len(topologies)
        n_mem = len(memories)
        
        fig, axes = plt.subplots(n_topo, n_mem, figsize=(5 * n_mem, 4 * n_topo),
                                  squeeze=False, sharex=True, sharey=True)
        
        colors = plt.cm.tab10(np.linspace(0, 1, len(senders) * len(receivers)))
        
        for ti, topo in enumerate(topologies):
            for mi, mem in enumerate(memories):
                ax = axes[ti][mi]
                cidx = 0
                
                for s in senders:
                    for r in receivers:
                        entry = lookup.get((topo, mem, s, r))
                        if entry and metric_key in entry['metrics']:
                            vals = entry['metrics'][metric_key]
                            rounds = range(1, len(vals) + 1)
                            ax.plot(rounds, vals, label=f'S{s}R{r}',
                                    color=colors[cidx], linewidth=1.5, markersize=2, marker='o')
                        cidx += 1
                
                ax.set_ylim(-0.05, 1.15)
                ax.axhline(y=0.5, color='gray', linestyle=':', alpha=0.3)
                ax.grid(True, alpha=0.2)
                
                if ti == 0:
                    ax.set_title(f'Mem={mem}', fontsize=11)
                if mi == 0:
                    ax.set_ylabel(f'{topo.upper()}\n{metric_title}', fontsize=10)
                if ti == n_topo - 1:
                    ax.set_xlabel('Round', fontsize=10)
                
                if ti == 0 and mi == n_mem - 1:
                    ax.legend(fontsize=7, loc='upper right', ncol=2)
        
        fig.suptitle(f'{metric_title} — Time Series by Topology × Memory', fontsize=14, fontweight='bold')
        plt.tight_layout(rect=[0, 0, 1, 0.95])
        
        path = os.path.join(summary_dir, f'faceted_{metric_slug}.png')
        fig.savefig(path, dpi=150)
        print(f"  Saved {path}")
        plt.close(fig)
    
    # ========================================
    # 3. PARAMETER EFFECT BAR CHARTS
    # ========================================
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    bar_metrics = [
        ('mean_deception_rate', 'Avg Deception Rate'),
        ('mean_trust_rate', 'Avg Trust Rate'),
        ('mean_deception_success', 'Avg Deception Success'),
        ('mean_receiver_accuracy', 'Avg Receiver Accuracy'),
    ]
    
    for ax_idx, (mk, mt) in enumerate(bar_metrics):
        ax = axes[ax_idx // 2][ax_idx % 2]
        
        # Compute marginal effect by each dimension
        dims = {
            'Topology': ('topology', topologies),
            'Memory': ('memory_limit', memories),
            'Senders': ('num_senders', senders),
            'Receivers': ('num_receivers', receivers),
        }
        
        x_positions = []
        x_labels = []
        bar_values = []
        bar_errors = []
        bar_colors = ['#2196F3', '#4CAF50', '#FF9800', '#E91E63']
        color_list = []
        
        offset = 0
        for di, (dim_name, (dim_key, dim_values)) in enumerate(dims.items()):
            for v in dim_values:
                vals = []
                for entry in data:
                    if entry['config'].get(dim_key) == v and mk in entry['metrics']:
                        series = entry['metrics'][mk]
                        valid = [x for x in series if x is not None]
                        if valid:
                            vals.append(np.mean(valid))
                
                x_positions.append(offset)
                x_labels.append(f'{dim_name}\n{v}')
                bar_values.append(np.mean(vals) if vals else 0)
                bar_errors.append(np.std(vals) if vals else 0)
                color_list.append(bar_colors[di])
                offset += 1
            offset += 0.5  # gap between dimension groups
        
        ax.bar(x_positions, bar_values, yerr=bar_errors, color=color_list,
               alpha=0.8, capsize=3, edgecolor='white', linewidth=0.5)
        ax.set_xticks(x_positions)
        ax.set_xticklabels(x_labels, fontsize=7, rotation=0)
        ax.set_ylabel(mt, fontsize=10)
        ax.set_ylim(0, 1)
        ax.grid(True, axis='y', alpha=0.3)
        ax.set_title(mt, fontsize=11, fontweight='bold')
    
    fig.suptitle('Parameter Effects on Signaling Game Metrics\n(marginal averages ± std)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout(rect=[0, 0, 1, 0.93])
    
    path = os.path.join(summary_dir, 'parameter_effects.png')
    fig.savefig(path, dpi=150)
    print(f"  Saved {path}")
    plt.close(fig)
    
    print(f"All summary plots saved to {summary_dir}/")


def plot_pgg_summary(file_path):
    """
    Generates publication-quality summary plots for large PGG sweeps.
    Faceted by observation_type × multiplier, lines for each agent count.
    """
    print(f"Generating PGG summary plots from {file_path}...")
    with open(file_path, 'r') as f:
        data = json.load(f)
    
    output_dir = os.path.dirname(file_path)
    summary_dir = os.path.join(output_dir, "summary_plots")
    os.makedirs(summary_dir, exist_ok=True)
    
    obs_types = sorted(set(e['config'].get('observation_type', 'full') for e in data))
    multipliers = sorted(set(e['config'].get('multiplier', 1.5) for e in data))
    agents_list = sorted(set(e['config'].get('num_agents', 3) for e in data))
    memories = sorted(set(e['config'].get('memory_limit', 3) for e in data))
    
    lookup = {}
    for entry in data:
        c = entry['config']
        key = (c.get('observation_type', 'full'), c.get('multiplier'), c.get('num_agents'), c.get('memory_limit'))
        lookup[key] = entry
    
    metric_defs = [
        ('mean_cooperation', 'Cooperation Rate', 'cooperation'),
        ('mean_entropy', 'Behavioral Entropy', 'entropy'),
        ('mean_defector_ratio', 'Defector Ratio', 'defector'),
    ]
    
    # Faceted time-series: rows=obs_type, cols=multiplier, lines=agents×memory
    for metric_key, metric_title, metric_slug in metric_defs:
        n_obs = len(obs_types)
        n_mult = len(multipliers)
        
        fig, axes = plt.subplots(n_obs, n_mult, figsize=(6 * n_mult, 4 * n_obs),
                                  squeeze=False, sharex=True, sharey=True)
        
        colors = plt.cm.Set2(np.linspace(0, 1, len(agents_list) * len(memories)))
        
        for oi, obs in enumerate(obs_types):
            for mi, mult in enumerate(multipliers):
                ax = axes[oi][mi]
                cidx = 0
                
                for n in agents_list:
                    for mem in memories:
                        entry = lookup.get((obs, mult, n, mem))
                        if entry and metric_key in entry['metrics']:
                            vals = entry['metrics'][metric_key]
                            rounds = range(1, len(vals) + 1)
                            ax.plot(rounds, vals, label=f'N{n} Mem{mem}',
                                    color=colors[cidx], linewidth=1.5, marker='o', markersize=2)
                        cidx += 1
                
                ax.set_ylim(-0.05, 1.15)
                if metric_slug == 'cooperation':
                    ax.axhline(y=0.0, color='red', linestyle=':', alpha=0.3, label='Nash Eq.')
                    ax.axhline(y=1.0, color='green', linestyle=':', alpha=0.3, label='Social Opt.')
                ax.grid(True, alpha=0.2)
                
                if oi == 0:
                    ax.set_title(f'M={mult}', fontsize=11)
                if mi == 0:
                    ax.set_ylabel(f'{obs.upper()}\n{metric_title}', fontsize=10)
                if oi == n_obs - 1:
                    ax.set_xlabel('Round', fontsize=10)
                
                if oi == 0 and mi == n_mult - 1:
                    ax.legend(fontsize=7, loc='best', ncol=2)
        
        fig.suptitle(f'{metric_title} — Faceted by Observation × Multiplier', fontsize=14, fontweight='bold')
        plt.tight_layout(rect=[0, 0, 1, 0.95])
        
        path = os.path.join(summary_dir, f'faceted_{metric_slug}.png')
        fig.savefig(path, dpi=150)
        print(f"  Saved {path}")
        plt.close(fig)
    
    print(f"All PGG summary plots saved to {summary_dir}/")


def auto_detect_and_plot(file_path):
    """Auto-detect environment type and call appropriate plot function."""
    with open(file_path, 'r') as f:
        data = json.load(f)
    
    if not data:
        print("Empty report file.")
        return
    
    n_configs = len(data)
    first_metrics = data[0].get('metrics', {})
    is_signaling = 'mean_deception_rate' in first_metrics
    
    if is_signaling:
        # Always generate the original per-line plots
        plot_signaling_results(file_path)
        # For large sweeps, also generate summary plots
        if n_configs > 8:
            print(f"\nLarge sweep detected ({n_configs} configs). Generating summary plots...")
            plot_signaling_summary(file_path)
    else:
        plot_sweep_results(file_path)
        if n_configs > 8:
            print(f"\nLarge sweep detected ({n_configs} configs). Generating summary plots...")
            plot_pgg_summary(file_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Visualize Experiment Results")
    parser.add_argument("file", type=str, help="Path to final_sweep_report.json")
    args = parser.parse_args()
    
    if os.path.exists(args.file):
        auto_detect_and_plot(args.file)
    else:
        print(f"File not found: {args.file}")
