import json
import matplotlib.pyplot as plt
import os
import argparse
import numpy as np

"""
Visualization module for Multi-Agent Experiment Results.

This script reads the JSON reports generated by 'experiment_runner.py' and produces
static plots (PNG) for key metrics like Cooperation Rate and Entropy.

Fix 7: Now includes Nash Equilibrium and Social Optimum reference lines.
Fix 8: Adds per-trial variance analysis (individual trial trajectories).
"""

def plot_sweep_results(file_path):
    """
    Generates plots from a given experiment report file.
    
    Args:
        file_path (str): Path to the 'final_sweep_report.json' file.
        
    Outputs:
        - cooperation_plot.png: Cooperation Rate vs Rounds (with theoretical baselines)
        - entropy_plot.png: Behavioral Entropy vs Rounds
        - per_trial_variance.png: Individual trial trajectories for each config
    """
    print(f"Loading results from {file_path}...")
    with open(file_path, 'r') as f:
        data = json.load(f)
    
    output_dir = os.path.dirname(file_path)
    
    # ========================================
    # 1. Cooperation Rate with Theoretical Baselines
    # ========================================
    plt.figure(figsize=(12, 7))
    
    for entry in data:
        config = entry['config']
        metrics = entry['metrics']
        
        rounds = range(1, len(metrics['mean_cooperation']) + 1)
        mean_coop = metrics['mean_cooperation']
        std_coop = metrics['std_cooperation']
        
        mem = config.get('memory_limit', '?')
        agent_type = config.get('agent_type', 'llm')
        label = f"N={config['num_agents']}, M={config['multiplier']}, Mem={mem}"
        if agent_type != "llm":
            label += f" [{agent_type}]"
        
        plt.plot(rounds, mean_coop, marker='o', label=label, markersize=3)
        plt.fill_between(rounds, 
                         np.array(mean_coop) - np.array(std_coop), 
                         np.array(mean_coop) + np.array(std_coop), 
                         alpha=0.1)

    # Theoretical baselines
    max_rounds = max(len(entry['metrics']['mean_cooperation']) for entry in data)
    x_line = range(1, max_rounds + 1)
    plt.axhline(y=1.0, color='green', linestyle=':', linewidth=1.5, alpha=0.7, label='Social Optimum (100%)')
    plt.axhline(y=0.0, color='red', linestyle=':', linewidth=1.5, alpha=0.7, label='Nash Equilibrium (0%)')
    plt.axhline(y=0.5, color='gray', linestyle=':', linewidth=1.0, alpha=0.5, label='Random Baseline (50%)')

    plt.title("Cooperation Rate over Rounds", fontsize=14)
    plt.xlabel("Round", fontsize=12)
    plt.ylabel("Avg Contribution % (normalized)", fontsize=12)
    plt.ylim(-0.05, 1.15)
    plt.legend(fontsize=8, loc='lower right')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    
    output_img = os.path.join(output_dir, "cooperation_plot.png")
    plt.savefig(output_img, dpi=150)
    print(f"Saved plot to {output_img}")
    plt.close()

    # ========================================
    # 2. Entropy over Time
    # ========================================
    plt.figure(figsize=(12, 7))
    
    for entry in data:
        config = entry['config']
        metrics = entry['metrics']
        
        rounds = range(1, len(metrics['mean_entropy']) + 1)
        mean_ent = metrics['mean_entropy']
        
        mem = config.get('memory_limit', '?')
        label = f"N={config['num_agents']}, M={config['multiplier']}, Mem={mem}"
        plt.plot(rounds, mean_ent, marker='s', linestyle='--', label=label, markersize=3)

    plt.title("Behavioral Entropy over Rounds", fontsize=14)
    plt.xlabel("Round", fontsize=12)
    plt.ylabel("Entropy (bits)", fontsize=12)
    plt.legend(fontsize=8)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    
    output_img_ent = os.path.join(output_dir, "entropy_plot.png")
    plt.savefig(output_img_ent, dpi=150)
    print(f"Saved plot to {output_img_ent}")
    plt.close()
    
    # ========================================
    # 3. Gini Coefficient over Time
    # ========================================
    has_gini = any('mean_gini' in entry['metrics'] for entry in data)
    if has_gini:
        plt.figure(figsize=(12, 7))
        
        for entry in data:
            config = entry['config']
            metrics = entry['metrics']
            if 'mean_gini' not in metrics:
                continue
            
            rounds = range(1, len(metrics['mean_gini']) + 1)
            mem = config.get('memory_limit', '?')
            label = f"N={config['num_agents']}, M={config['multiplier']}, Mem={mem}"
            plt.plot(rounds, metrics['mean_gini'], marker='^', linestyle='-', label=label, markersize=3)

        plt.title("Reward Inequality (Gini Coefficient) over Rounds", fontsize=14)
        plt.xlabel("Round", fontsize=12)
        plt.ylabel("Gini Coefficient", fontsize=12)
        plt.ylim(-0.01, 0.5)
        plt.axhline(y=0.0, color='green', linestyle=':', alpha=0.5, label='Perfect Equality')
        plt.legend(fontsize=8)
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        
        output_img_gini = os.path.join(output_dir, "gini_plot.png")
        plt.savefig(output_img_gini, dpi=150)
        print(f"Saved plot to {output_img_gini}")
        plt.close()
    
    # ========================================
    # 4. Defector Ratio over Time
    # ========================================
    has_defector = any('mean_defector_ratio' in entry['metrics'] for entry in data)
    if has_defector:
        plt.figure(figsize=(12, 7))
        
        for entry in data:
            config = entry['config']
            metrics = entry['metrics']
            if 'mean_defector_ratio' not in metrics:
                continue
            
            rounds = range(1, len(metrics['mean_defector_ratio']) + 1)
            mem = config.get('memory_limit', '?')
            label = f"N={config['num_agents']}, M={config['multiplier']}, Mem={mem}"
            plt.plot(rounds, metrics['mean_defector_ratio'], marker='v', linestyle='-', label=label, markersize=3)

        plt.title("Defector Ratio over Rounds", fontsize=14)
        plt.xlabel("Round", fontsize=12)
        plt.ylabel("Fraction of Agents Contributing 0", fontsize=12)
        plt.ylim(-0.05, 1.05)
        plt.legend(fontsize=8)
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        
        output_img_def = os.path.join(output_dir, "defector_plot.png")
        plt.savefig(output_img_def, dpi=150)
        print(f"Saved plot to {output_img_def}")
        plt.close()
    
    # ========================================
    # 5. Convergence Summary (text report)
    # ========================================
    has_convergence = any('mean_time_to_convergence' in entry['metrics'] for entry in data)
    if has_convergence:
        summary_path = os.path.join(output_dir, "convergence_summary.txt")
        with open(summary_path, "w") as f:
            f.write("Convergence Summary\n")
            f.write("=" * 60 + "\n\n")
            f.write(f"{'Config':<30} {'Conv. Rate':>10} {'Mean Round':>12} {'Change Pts':>12}\n")
            f.write("-" * 64 + "\n")
            for entry in data:
                config = entry['config']
                metrics = entry['metrics']
                mem = config.get('memory_limit', '?')
                label = f"N={config['num_agents']}, M={config['multiplier']}, Mem={mem}"
                conv_rate = metrics.get('convergence_rate', 0)
                mean_conv = metrics.get('mean_time_to_convergence')
                change_pts = metrics.get('total_change_points', 0)
                
                conv_str = f"{mean_conv:.1f}" if mean_conv is not None else "N/A"
                f.write(f"{label:<30} {conv_rate:>9.0%} {conv_str:>12} {change_pts:>12}\n")
        print(f"Saved convergence summary to {summary_path}")
    
    # ========================================
    # 6. Per-Trial Variance Analysis
    # ========================================
    # Load raw trial data and plot individual trial trajectories
    raw_files = [f for f in os.listdir(output_dir) if f.startswith("raw_") and f.endswith(".json")]
    
    if raw_files:
        n_configs = len(raw_files)
        cols = min(3, n_configs)
        rows = (n_configs + cols - 1) // cols
        fig, axes = plt.subplots(rows, cols, figsize=(6 * cols, 4 * rows), squeeze=False)
        
        for idx, raw_file in enumerate(sorted(raw_files)):
            row, col = divmod(idx, cols)
            ax = axes[row][col]
            
            config_key = raw_file[len("raw_"):-len(".json")]
            
            with open(os.path.join(output_dir, raw_file), 'r') as f:
                trials = json.load(f)
            
            # Plot each trial's cooperation trajectory
            for trial in trials:
                coop = trial['metrics']['cooperation_rates']
                rounds = range(1, len(coop) + 1)
                ax.plot(rounds, coop, alpha=0.2, linewidth=0.8, color='blue')
            
            # Plot the mean
            if trials:
                all_coop = [t['metrics']['cooperation_rates'] for t in trials]
                mean_coop = np.mean(all_coop, axis=0)
                ax.plot(range(1, len(mean_coop) + 1), mean_coop, 
                       color='red', linewidth=2, label='Mean')
            
            ax.set_title(config_key, fontsize=10)
            ax.set_ylim(-0.05, 1.15)
            ax.axhline(y=0.0, color='red', linestyle=':', alpha=0.3)
            ax.axhline(y=1.0, color='green', linestyle=':', alpha=0.3)
            ax.grid(True, alpha=0.2)
            ax.legend(fontsize=7)
        
        # Hide empty subplots
        for idx in range(n_configs, rows * cols):
            row, col = divmod(idx, cols)
            axes[row][col].set_visible(False)
        
        fig.suptitle("Per-Trial Cooperation Trajectories", fontsize=14)
        plt.tight_layout()
        
        output_img_var = os.path.join(output_dir, "per_trial_variance.png")
        fig.savefig(output_img_var, dpi=150)
        print(f"Saved plot to {output_img_var}")
        plt.close(fig)
    
    print("All plots generated successfully.")


def plot_signaling_results(file_path):
    """
    Generates plots from a signaling game sweep report.
    
    Outputs:
        - deception_plot.png: Deception Rate over Rounds
        - trust_plot.png: Trust Rate over Rounds
        - deception_success_plot.png: Deception Success Rate
        - receiver_accuracy_plot.png: Receiver Accuracy
    """
    print(f"Loading signaling results from {file_path}...")
    with open(file_path, 'r') as f:
        data = json.load(f)
    
    output_dir = os.path.dirname(file_path)
    
    def _make_label(config):
        s = config.get('num_senders', '?')
        r = config.get('num_receivers', '?')
        t = config.get('topology', '?')
        m = config.get('memory_limit', '?')
        return f"S={s}, R={r}, T={t}, Mem={m}"
    
    # ========================================
    # 1. Deception Rate
    # ========================================
    plt.figure(figsize=(12, 7))
    for entry in data:
        config = entry['config']
        met = entry['metrics']
        if 'mean_deception_rate' not in met:
            continue
        rounds = range(1, len(met['mean_deception_rate']) + 1)
        label = _make_label(config)
        plt.plot(rounds, met['mean_deception_rate'], marker='o', label=label, markersize=3)
        if 'std_deception_rate' in met:
            plt.fill_between(rounds,
                             np.array(met['mean_deception_rate']) - np.array(met['std_deception_rate']),
                             np.array(met['mean_deception_rate']) + np.array(met['std_deception_rate']),
                             alpha=0.1)
    
    plt.axhline(y=0.0, color='green', linestyle=':', alpha=0.5, label='Perfect Truth-Telling')
    plt.axhline(y=1.0, color='red', linestyle=':', alpha=0.5, label='Total Deception')
    plt.axhline(y=0.5, color='gray', linestyle=':', alpha=0.3, label='Random')
    plt.title("Deception Rate over Rounds", fontsize=14)
    plt.xlabel("Round", fontsize=12)
    plt.ylabel("Fraction of Deceptive Messages", fontsize=12)
    plt.ylim(-0.05, 1.15)
    plt.legend(fontsize=7, loc='best')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "deception_plot.png"), dpi=150)
    print(f"Saved deception_plot.png")
    plt.close()
    
    # ========================================
    # 2. Trust Rate
    # ========================================
    plt.figure(figsize=(12, 7))
    for entry in data:
        config = entry['config']
        met = entry['metrics']
        if 'mean_trust_rate' not in met:
            continue
        rounds = range(1, len(met['mean_trust_rate']) + 1)
        label = _make_label(config)
        plt.plot(rounds, met['mean_trust_rate'], marker='s', linestyle='--', label=label, markersize=3)
    
    plt.axhline(y=1.0, color='blue', linestyle=':', alpha=0.5, label='Always Invest')
    plt.axhline(y=0.0, color='orange', linestyle=':', alpha=0.5, label='Always Pass')
    plt.title("Trust Rate (All Receivers) over Rounds", fontsize=14)
    plt.xlabel("Round", fontsize=12)
    plt.ylabel("Fraction of Receivers Investing", fontsize=12)
    plt.ylim(-0.05, 1.15)
    plt.legend(fontsize=7, loc='best')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "trust_plot.png"), dpi=150)
    print(f"Saved trust_plot.png")
    plt.close()
    
    # ========================================
    # 2b. Informed Trust Rate (excludes empty-inbox receivers)
    # ========================================
    has_informed = any('mean_informed_trust_rate' in entry['metrics'] for entry in data)
    if has_informed:
        plt.figure(figsize=(12, 7))
        for entry in data:
            config = entry['config']
            met = entry['metrics']
            informed = met.get('mean_informed_trust_rate', [])
            if not informed:
                continue
            # Filter None values for plotting
            rounds_plot = [r + 1 for r, v in enumerate(informed) if v is not None]
            vals_plot = [v for v in informed if v is not None]
            if not rounds_plot:
                continue
            label = _make_label(config)
            plt.plot(rounds_plot, vals_plot, marker='s', linestyle='--', label=label, markersize=3)

        plt.axhline(y=1.0, color='blue', linestyle=':', alpha=0.5, label='Always Invest')
        plt.axhline(y=0.0, color='orange', linestyle=':', alpha=0.5, label='Always Pass')
        plt.title("Informed Trust Rate over Rounds\n(Excludes receivers with no messages)", fontsize=14)
        plt.xlabel("Round", fontsize=12)
        plt.ylabel("Fraction of Informed Receivers Investing", fontsize=12)
        plt.ylim(-0.05, 1.15)
        plt.legend(fontsize=7, loc='best')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "informed_trust_plot.png"), dpi=150)
        print(f"Saved informed_trust_plot.png")
        plt.close()
    
    # ========================================
    # 3. Deception Success Rate
    # ========================================
    has_success = any('mean_deception_success' in entry['metrics'] for entry in data)
    if has_success:
        plt.figure(figsize=(12, 7))
        for entry in data:
            config = entry['config']
            met = entry['metrics']
            if 'mean_deception_success' not in met:
                continue
            rounds = range(1, len(met['mean_deception_success']) + 1)
            label = _make_label(config)
            plt.plot(rounds, met['mean_deception_success'], marker='^', label=label, markersize=3)
        
        plt.title("Deception Success Rate over Rounds", fontsize=14)
        plt.xlabel("Round", fontsize=12)
        plt.ylabel("Fraction of Lies → Invest", fontsize=12)
        plt.ylim(-0.05, 1.15)
        plt.legend(fontsize=7, loc='best')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "deception_success_plot.png"), dpi=150)
        print(f"Saved deception_success_plot.png")
        plt.close()
    
    # ========================================
    # 4. Receiver Accuracy
    # ========================================
    has_accuracy = any('mean_receiver_accuracy' in entry['metrics'] for entry in data)
    if has_accuracy:
        plt.figure(figsize=(12, 7))
        for entry in data:
            config = entry['config']
            met = entry['metrics']
            if 'mean_receiver_accuracy' not in met:
                continue
            rounds = range(1, len(met['mean_receiver_accuracy']) + 1)
            label = _make_label(config)
            plt.plot(rounds, met['mean_receiver_accuracy'], marker='D', label=label, markersize=3)
        
        plt.axhline(y=0.5, color='gray', linestyle=':', alpha=0.3, label='Random Accuracy')
        plt.title("Receiver Accuracy over Rounds", fontsize=14)
        plt.xlabel("Round", fontsize=12)
        plt.ylabel("Fraction of Optimal Decisions", fontsize=12)
        plt.ylim(-0.05, 1.15)
        plt.legend(fontsize=7, loc='best')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "receiver_accuracy_plot.png"), dpi=150)
        print(f"Saved receiver_accuracy_plot.png")
        plt.close()
    
    # ========================================
    # 5. Convergence Summary (text)
    # ========================================
    summary_path = os.path.join(output_dir, "convergence_summary.txt")
    with open(summary_path, "w") as f:
        f.write("Signaling Game Convergence Summary\n")
        f.write("=" * 70 + "\n\n")
        f.write(f"{'Config':<40} {'Conv. Rate':>10} {'Mean Round':>12} {'Change Pts':>12}\n")
        f.write("-" * 74 + "\n")
        for entry in data:
            config = entry['config']
            met = entry['metrics']
            label = _make_label(config)
            conv_rate = met.get('convergence_rate', 0)
            mean_conv = met.get('mean_time_to_convergence')
            change_pts = met.get('total_change_points', 0)
            conv_str = f"{mean_conv:.1f}" if mean_conv is not None else "N/A"
            f.write(f"{label:<40} {conv_rate:>9.0%} {conv_str:>12} {change_pts:>12}\n")
    print(f"Saved convergence summary to {summary_path}")
    
    print("All signaling game plots generated successfully.")


def auto_detect_and_plot(file_path):
    """Auto-detect environment type and call appropriate plot function."""
    with open(file_path, 'r') as f:
        data = json.load(f)
    
    if not data:
        print("Empty report file.")
        return
    
    # Detect by checking first entry's metric keys
    first_metrics = data[0].get('metrics', {})
    if 'mean_deception_rate' in first_metrics:
        plot_signaling_results(file_path)
    else:
        plot_sweep_results(file_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Visualize Experiment Results")
    parser.add_argument("file", type=str, help="Path to final_sweep_report.json")
    args = parser.parse_args()
    
    if os.path.exists(args.file):
        auto_detect_and_plot(args.file)
    else:
        print(f"File not found: {args.file}")
